#!/usr/bin/env python3
"""
Phase 1 编号 3-4 LaTeX 导出：merged CSV + 7B CSV → booktabs 表格

读取:
  - results/phase1_summary_merged.csv  (1.5B v1+v2, kivi_style 来自 v2)
  - results/phase1_summary_7b.csv      (7B cross-model 复核)

产出两张 thesis Ch4 §4.x 可 include 的 .tex：
  - phase1_official_longbench_1p5b.tex
  - phase1_official_longbench_7b.tex
+ 一份 cross-model 一致性脚注总结（判据 2 Gate 数据）

用法:
  python3 scripts/export_phase1_latex.py \
    --summary_1p5b results/phase1_summary_merged.csv \
    --summary_7b results/phase1_summary_7b.csv \
    --out_dir thesis/tables/
"""
import argparse
import csv
from collections import defaultdict
from pathlib import Path

MODE_ORDER = ["fp16", "int8_ours", "kivi_style", "int4_ours_asym"]
MODE_LATEX_LABEL = {
    "fp16":           r"FP16 (baseline)",
    "int8_ours":      r"INT8-ours",
    "kivi_style":     r"KIVI-style",
    "int4_ours_asym": r"INT4-RoleAlign",
}

TASK_ORDER = ["narrativeqa", "hotpotqa", "gov_report"]
TASK_LABEL = {
    "narrativeqa": "NarrativeQA",
    "hotpotqa":    "HotpotQA",
    "gov_report":  "GovReport",
}
METRIC_LABEL = {"f1": "F1", "rouge_l": "ROUGE-L"}


def load_rows(path: Path):
    if not path.exists():
        return []
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def build_table(rows, model_label: str, table_label: str, caption: str, footnote: str = ""):
    by_task = defaultdict(dict)
    for r in rows:
        by_task[r["task"]][r["kv_mode"]] = r

    lines = []
    lines.append(f"% Auto-generated by scripts/export_phase1_latex.py — {model_label}")
    lines.append(r"\begin{table}[!htbp]")
    lines.append(r"\centering")
    lines.append(rf"\caption{{{caption}}}")
    lines.append(rf"\label{{{table_label}}}")
    header = ["任务", "指标"] + [MODE_LATEX_LABEL[m] for m in MODE_ORDER]
    lines.append(r"\begin{tabular}{ll" + "r" * len(MODE_ORDER) + "}")
    lines.append(r"\toprule")
    lines.append(" & ".join(header) + r" \\")
    lines.append(r"\midrule")

    for task in TASK_ORDER:
        if task not in by_task:
            continue
        mode_rows = by_task[task]
        any_r = next(iter(mode_rows.values()))
        metric_raw = any_r.get("metric_name", "?")
        metric = METRIC_LABEL.get(metric_raw, metric_raw)

        cells = [TASK_LABEL.get(task, task), metric]
        fp16_score = None
        for m in MODE_ORDER:
            if m in mode_rows:
                try:
                    s = float(mode_rows[m]["score"])
                    cells.append(f"{s:.2f}")
                    if m == "fp16":
                        fp16_score = s
                except (ValueError, TypeError):
                    cells.append("--")
            else:
                cells.append("--")
        lines.append(" & ".join(cells) + r" \\")

        if fp16_score is not None and fp16_score != 0:
            delta_cells = [r"$\hookrightarrow \Delta_{\text{FP16}}$", ""]
            for m in MODE_ORDER:
                if m == "fp16":
                    delta_cells.append("(基线)")
                elif m in mode_rows:
                    try:
                        s = float(mode_rows[m]["score"])
                        d = (s - fp16_score) / fp16_score * 100
                        sign = "+" if d >= 0 else ""
                        delta_cells.append(f"{sign}{d:.1f}\\%")
                    except (ValueError, TypeError):
                        delta_cells.append("--")
                else:
                    delta_cells.append("--")
            lines.append(" & ".join(delta_cells) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    if footnote:
        lines.append(rf"% {footnote}")
    lines.append(r"\end{table}")
    lines.append("")
    return "\n".join(lines)


def compute_cross_model_summary(rows_1p5b, rows_7b):
    """Build per-mode 1.5B↔7B consistency summary (判据 2 data)."""
    by_mode_1p5b = defaultdict(list)
    by_mode_7b = defaultdict(list)

    def to_deg_map(rows):
        by_task = defaultdict(dict)
        for r in rows:
            by_task[r["task"]][r["kv_mode"]] = r
        deg = defaultdict(dict)
        for task, modes in by_task.items():
            if "fp16" not in modes:
                continue
            try:
                fp16 = float(modes["fp16"]["score"])
            except (ValueError, TypeError):
                continue
            if fp16 == 0:
                continue
            for m, r in modes.items():
                if m == "fp16":
                    continue
                try:
                    s = float(r["score"])
                    deg[task][m] = (fp16 - s) / fp16 * 100
                except (ValueError, TypeError):
                    pass
        return deg

    deg_1p5b = to_deg_map(rows_1p5b)
    deg_7b = to_deg_map(rows_7b)

    # 聚合到 per-mode 平均退化率
    for task, modes in deg_1p5b.items():
        for m, d in modes.items():
            by_mode_1p5b[m].append(d)
    for task, modes in deg_7b.items():
        for m, d in modes.items():
            by_mode_7b[m].append(d)

    lines = []
    lines.append(r"% Cross-model consistency summary (Gate 5 判据 2)")
    lines.append(r"\begin{table}[!htbp]")
    lines.append(r"\centering")
    lines.append(r"\caption{1.5B↔7B 跨模型退化率一致性（Gate 5 判据 2；正值=退化，负值=提升）。}")
    lines.append(r"\label{tab:phase1-cross-model-consistency}")
    lines.append(r"\begin{tabular}{lrrl}")
    lines.append(r"\toprule")
    lines.append(r"量化模式 & 1.5B 平均 & 7B 平均 & 一致性 \\")
    lines.append(r"\midrule")
    for m in ["int8_ours", "kivi_style", "int4_ours_asym"]:
        d_1p5b = sum(by_mode_1p5b[m]) / len(by_mode_1p5b[m]) if by_mode_1p5b.get(m) else None
        d_7b = sum(by_mode_7b[m]) / len(by_mode_7b[m]) if by_mode_7b.get(m) else None
        if d_1p5b is None or d_7b is None:
            continue
        same_sign = (d_1p5b * d_7b > 0) or (abs(d_1p5b) < 2 and abs(d_7b) < 2)
        consistency = r"\checkmark" if same_sign else r"$\circ$"
        sign1 = "+" if d_1p5b >= 0 else ""
        sign7 = "+" if d_7b >= 0 else ""
        lines.append(
            f"{MODE_LATEX_LABEL[m]} & {sign1}{d_1p5b:.1f}\\% & {sign7}{d_7b:.1f}\\% & {consistency} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--summary_1p5b", required=True, type=Path)
    ap.add_argument("--summary_7b", required=True, type=Path)
    ap.add_argument("--out_dir", required=True, type=Path)
    args = ap.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows_1p5b = load_rows(args.summary_1p5b)
    rows_7b = load_rows(args.summary_7b)

    # 1.5B 主表
    tex_1p5b = build_table(
        rows_1p5b,
        model_label="Qwen2.5-1.5B",
        table_label="tab:phase1-official-longbench-1p5b",
        caption=(r"Qwen2.5-1.5B-Instruct 在官方 LongBench 三任务上的跨 kv\_mode 对比 "
                 r"（$n=50$，seq\_len=4K，greedy，官方 jsonl 数据源）。"
                 r"KIVI-style 数据来自 ENG-045-v2 补丁后重跑（修前/修后分数精确一致）。"),
        footnote="Phase 1 编号 2-3 主结果；Gate 5 判据 1 (<20% 退化) 的证据基础。",
    )
    out_1p5b = args.out_dir / "phase1_official_longbench_1p5b.tex"
    out_1p5b.write_text(tex_1p5b, encoding="utf-8")
    print(f"Wrote {out_1p5b}")

    # 7B 主表
    tex_7b = build_table(
        rows_7b,
        model_label="Qwen2.5-7B",
        table_label="tab:phase1-official-longbench-7b",
        caption=(r"Qwen2.5-7B-Instruct 在官方 LongBench 三任务上的跨 kv\_mode 对比（$n=50$）。"
                 r"跨模型复核验证 fixed-bit 路线在 $H_{kv}=4$ 下的一致性。"),
        footnote="Phase 1 编号 4 产出；Gate 5 判据 2 (跨模型一致性) 的证据基础。",
    )
    out_7b = args.out_dir / "phase1_official_longbench_7b.tex"
    out_7b.write_text(tex_7b, encoding="utf-8")
    print(f"Wrote {out_7b}")

    # Cross-model consistency summary
    tex_cross = compute_cross_model_summary(rows_1p5b, rows_7b)
    out_cross = args.out_dir / "phase1_cross_model_consistency.tex"
    out_cross.write_text(tex_cross, encoding="utf-8")
    print(f"Wrote {out_cross}")

    print()
    print("Phase 1 LaTeX 导出完成——可在 thesis 用 \\input{tables/phase1_official_longbench_1p5b.tex} 等引入")


if __name__ == "__main__":
    main()
