#!/usr/bin/env python3
"""
Phase 2 编号 6 LaTeX 导出：phase2_summary.csv → booktabs 表格

读取 results/phase2_summary.csv（aggregate_phase2.py 产出，含 policy_name 主键），
渲染成论文 Ch4 §4.y 可 include 的 .tex 片段。

用法:
  python3 scripts/export_phase2_latex.py \
    --summary results/phase2_summary.csv \
    --out_tex thesis/tables/phase2_allocator_main.tex

产出 LaTeX 包含：
  - 主表（task × 5 policy）带官方 metric + Δ vs Uniform INT4
  - gate 判定结论（BAKV > Random 的 task 数）
  - caption 含 avg_bits + protected_layers 信息
"""
import argparse
import csv
from collections import defaultdict
from pathlib import Path

POLICY_ORDER = [
    "uniform_int4_k4v4",
    "uniform_int8_k8v8",
    "bakv_top3",
    "heuristic_top3",
    "random3_seed42",
]

POLICY_LATEX_LABEL = {
    "uniform_int4_k4v4": r"Uniform INT4",
    "uniform_int8_k8v8": r"Uniform INT8",
    "bakv_top3":         r"BAKV Top-3",
    "heuristic_top3":    r"Heuristic-3",
    "random3_seed42":    r"Random-3",
}

# 固定任务顺序与 metric 标签
TASK_ORDER = ["narrativeqa", "hotpotqa", "gov_report"]
TASK_LABEL = {
    "narrativeqa": "NarrativeQA",
    "hotpotqa":    "HotpotQA",
    "gov_report":  "GovReport",
}
METRIC_LABEL = {"f1": "F1", "rouge_l": "ROUGE-L"}


def load_rows(path: Path):
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def build_latex(rows):
    by_task = defaultdict(dict)  # by_task[task][policy] = row
    for r in rows:
        if not r.get("policy_name"):
            continue
        by_task[r["task"]][r["policy_name"]] = r

    lines = []
    lines.append(r"% Auto-generated by scripts/export_phase2_latex.py")
    lines.append(r"% Phase 2 编号 6 Allocator MVP 主表")
    lines.append(r"")
    lines.append(r"\begin{table}[!htbp]")
    lines.append(r"\centering")
    lines.append(r"\caption{Phase 2 Allocator MVP：Qwen2.5-1.5B-Instruct 在官方 LongBench 上 "
                 r"5 种 allocator policy 的跨任务对比（$n=50$，seq\_len=4K，greedy）。"
                 r"非 uniform policy 的 avg\_bits=4.429（3 层保 INT8 + 25 层 INT4），"
                 r"BAKV 保护层 $\{0,1,15\}$、Heuristic 保护 $\{0,14,27\}$、Random 保护 $\{2,18,20\}$。}")
    lines.append(r"\label{tab:phase2-allocator-mvp-1p5b}")
    header = ["任务", "指标"] + [POLICY_LATEX_LABEL[p] for p in POLICY_ORDER]
    lines.append(r"\begin{tabular}{ll" + "r" * len(POLICY_ORDER) + "}")
    lines.append(r"\toprule")
    lines.append(" & ".join(header) + r" \\")
    lines.append(r"\midrule")

    for task in TASK_ORDER:
        if task not in by_task:
            continue
        mode_rows = by_task[task]
        any_r = next(iter(mode_rows.values()))
        metric_raw = any_r.get("metric_name", "?")
        metric = METRIC_LABEL.get(metric_raw, metric_raw)

        cells = [TASK_LABEL.get(task, task), metric]
        ref_score = None
        for p in POLICY_ORDER:
            if p in mode_rows:
                try:
                    s = float(mode_rows[p]["score"])
                    cells.append(f"{s:.2f}")
                    if p == "uniform_int4_k4v4":
                        ref_score = s
                except (ValueError, TypeError):
                    cells.append("--")
            else:
                cells.append("--")
        lines.append(" & ".join(cells) + r" \\")

        # Δ vs Uniform INT4（下界参考）
        if ref_score is not None and ref_score != 0:
            delta_cells = [r"$\hookrightarrow \Delta_{\text{UI4}}$", ""]
            for p in POLICY_ORDER:
                if p == "uniform_int4_k4v4":
                    delta_cells.append(r"(基线)")
                elif p in mode_rows:
                    try:
                        s = float(mode_rows[p]["score"])
                        d = (s - ref_score) / ref_score * 100
                        sign = "+" if d >= 0 else ""
                        delta_cells.append(f"{sign}{d:.1f}\\%")
                    except (ValueError, TypeError):
                        delta_cells.append("--")
                else:
                    delta_cells.append("--")
            lines.append(" & ".join(delta_cells) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    lines.append(r"")

    # Gate 判定注脚
    bakv_wins_random = 0
    bakv_wins_heuristic = 0
    total = 0
    bakv_sum, random_sum, heur_sum = 0.0, 0.0, 0.0
    for task in TASK_ORDER:
        if task not in by_task:
            continue
        mode_rows = by_task[task]
        try:
            b = float(mode_rows["bakv_top3"]["score"])
            r = float(mode_rows["random3_seed42"]["score"])
            total += 1
            bakv_sum += b
            random_sum += r
            if b > r:
                bakv_wins_random += 1
            if "heuristic_top3" in mode_rows:
                h = float(mode_rows["heuristic_top3"]["score"])
                heur_sum += h
                if b > h:
                    bakv_wins_heuristic += 1
        except (KeyError, ValueError, TypeError):
            continue

    if total > 0:
        lines.append(r"% Gate 判定注脚：")
        lines.append(
            f"% 硬 Gate（BAKV > Random 且 >=2/3 tasks 胜）: "
            f"BAKV 平均 {bakv_sum/total:.2f} vs Random 平均 {random_sum/total:.2f}, "
            f"BAKV 胜 {bakv_wins_random}/{total} tasks → "
            f"{'PASS' if (bakv_sum > random_sum and bakv_wins_random >= 2) else 'FAIL'}"
        )
        if total >= 1:
            lines.append(
                f"% 次 Gate（BAKV > Heuristic）: "
                f"Heuristic 平均 {heur_sum/total:.2f}, BAKV 胜 {bakv_wins_heuristic}/{total} tasks"
            )

    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--summary", required=True, type=Path, help="phase2_summary.csv path")
    ap.add_argument("--out_tex", required=True, type=Path)
    args = ap.parse_args()

    rows = load_rows(args.summary)
    tex = build_latex(rows)
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(tex, encoding="utf-8")
    print(f"Wrote LaTeX table to {args.out_tex}")
    print()
    print(tex)


if __name__ == "__main__":
    main()
