#!/bin/bash
# Gate 0.4: Generate v3 calibration artifacts for all 3 models (with RoPE fix)
# + INT8 v5_fixed for Exp-2 comparison
# Run on remote GPU server. Uses 3 GPUs in parallel.
# Usage: bash scripts/gate0_generate_v3_calib.sh
set -euo pipefail
cd /root/LLM_KVCache_Quantization
source /etc/network_turbo 2>/dev/null || true
export HF_HUB_OFFLINE=1

echo "=== Gate 0.4: v3 calibration generation (3 GPUs) ==="
echo "Start: $(date)"

# 1.5B already generated by smoke test — verify it exists
if [ ! -f "artifacts/kv_calib_rolealign_1p5b_v3.json" ]; then
  echo "FATAL: 1.5B v3 artifact missing (smoke test should have created it)" >&2
  exit 1
fi
echo ">>> 1.5B v3: already exists (from smoke test)"

# 7B on GPU-1
echo ">>> Starting 7B v3 calibration on GPU-1"
CUDA_VISIBLE_DEVICES=1 python3 scripts/calibrate_behavior.py \
  --model_id Qwen/Qwen2.5-7B-Instruct \
  --role_aware_axes \
  --role_aware_k_percentile_candidates "95.0,97.0,99.0,99.5,99.9,100.0" \
  --samples 128 --seq_len 512 --seed 1234 \
  --calib_out artifacts/kv_calib_rolealign_7b_v3.json \
  2>&1 | tee logs/recalib_7b_v3.log &
PID_7B=$!

# 8B on GPU-2
echo ">>> Starting 8B v3 calibration on GPU-2"
CUDA_VISIBLE_DEVICES=2 python3 scripts/calibrate_behavior.py \
  --model_id /root/autodl-tmp/modelscope_cache/LLM-Research/Meta-Llama-3___1-8B-Instruct \
  --role_aware_axes \
  --role_aware_k_percentile_candidates "95.0,97.0,99.0,99.5,99.9,100.0" \
  --samples 128 --seq_len 512 --seed 1234 \
  --calib_out artifacts/kv_calib_rolealign_8b_v3.json \
  2>&1 | tee logs/recalib_8b_v3.log &
PID_8B=$!

# INT8 v5_fixed on GPU-0 (for Exp-2 comparison)
echo ">>> Starting INT8 v5_fixed calibration on GPU-0"
CUDA_VISIBLE_DEVICES=0 python3 scripts/calibrate_behavior.py \
  --model_id Qwen/Qwen2.5-1.5B-Instruct \
  --loss_function kl --quant_bits 8 \
  --samples 128 --seq_len 512 \
  --calib_out artifacts/kv_calib_kl_1p5b_int8_v5_fixed.json \
  2>&1 | tee logs/recalib_int8_v5.log &
PID_INT8=$!

echo ">>> PIDs: 7B=$PID_7B, 8B=$PID_8B, INT8=$PID_INT8"

# Wait and check
FAIL=0
wait $PID_INT8 && echo ">>> INT8 v5 done: $(date)" || { echo ">>> INT8 v5 FAILED"; FAIL=1; }
wait $PID_7B   && echo ">>> 7B v3 done: $(date)"   || { echo ">>> 7B v3 FAILED"; FAIL=1; }
wait $PID_8B   && echo ">>> 8B v3 done: $(date)"   || { echo ">>> 8B v3 FAILED"; FAIL=1; }

if [ "$FAIL" -ne 0 ]; then
  echo "FATAL: One or more calibrations failed." >&2
  exit 1
fi

# Verify all artifacts
echo ""
echo "=== Verification ==="
for f in artifacts/kv_calib_rolealign_1p5b_v3.json \
         artifacts/kv_calib_rolealign_7b_v3.json \
         artifacts/kv_calib_rolealign_8b_v3.json \
         artifacts/kv_calib_kl_1p5b_int8_v5_fixed.json; do
  if [ -f "$f" ]; then
    echo "OK: $f ($(stat -c%s "$f") bytes)"
  else
    echo "MISSING: $f"
    FAIL=1
  fi
done

if [ "$FAIL" -ne 0 ]; then
  echo "FATAL: Some artifacts missing after calibration." >&2
  exit 1
fi

echo ""
echo "=========================================="
echo "  Gate 0.4 ALL DONE"
echo "  $(date)"
echo "=========================================="
