$pdf_mode = 5;           # use xelatex -> pdf
$xelatex = 'xelatex -synctex=1 -interaction=nonstopmode -file-line-error %O %S';
$bibtex_use = 2;
$clean_ext = 'synctex.gz synctex.gz(busy) run.xml aux bbl bcf blg fdb_latexmk fls log out toc lof lot xdv';
